version: '3.1'

networks:
  misp-backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "mispbr0"
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: "192.168.66.0/28"

volumes:
  misp-source:

services:
  misp:
    build: misp
    image: misp
    restart: unless-stopped
    volumes:
      - misp-source:/var/www/MISP
    networks:
      misp-backend:
        aliases:
          - misp
  frontend:
    build: frontend
    image: misp-fe
    restart: unless-stopped
    volumes:
      - misp-source:/var/www/MISP
    ports:
      - 80:80
      - 443:443
    networks:
      misp-backend:
        aliases:
          - frontend

  database:
    build: db
    image: misp-db
    depends_on:
      - misp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: misp
      MYSQL_USER: misp
      MYSQL_PASSWORD: password
    networks:
      misp-backend:
        aliases:
          - database

  modules:
    build: modules
    image: misp-modules
    restart: always
    networks:
      misp-backend:
        aliases:
          - misp-modules


  redis:
    image: redis:5
    restart: always
    networks:
      misp-backend:
        aliases:
          - redis


  worker_default:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue default --log-handler Console -v -d'" 

  worker_email:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue email --log-handler Console -v -d'" 

  worker_prio:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue prio --log-handler Console -v -d'" 

  worker_cache:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue cache--log-handler Console -v -d'" 

