version: '3.4'

networks:
  misp-backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "mispbr0"
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: "192.168.66.0/24"

volumes:
  misp-source:
  misp-config:
  misp-certificates:
  misp-logs:
  misp-app-tmp:
  misp-app-files:
  misp-database:

x-worker:
  &worker-container
  image: misp:${MISP_VERSION}
  pid: "service:misp"
  restart: always
  volumes:
    - misp-source:/var/www/MISP:rw
    - misp-config:/var/www/MISP/app/Config
    - misp-app-tmp:/var/www/MISP/app/tmp      
  depends_on:
    - misp
  networks:
    misp-backend:
  working_dir: "/var/www/MISP/app/Console/Command"
  entrypoint: "/bin/bash"
  env_file:
    - .worker.env
  command: ["/exec.sh", "../cake", "CakeResque.CakeResque", "start", "--interval", "5", "--queue", "$${queue}", "--log-handler", "Docker"] 

services:
  misp:
    build:
      context: ./misp
      args:
        MISP_TAG: ${MISP_VERSION}
    image: misp:${MISP_VERSION}
    restart: unless-stopped
    volumes:
      - misp-source:/var/www/MISP
      - misp-config:/var/www/MISP/app/Config
      - misp-app-files:/var/www/MISP/app/files
      - misp-app-tmp:/var/www/MISP/app/tmp
    networks:
      misp-backend:
        aliases:
          - ${MISP_CONTAINER_ALIAS}
    env_file:
      - .worker.env 
      - .env

  frontend:
    build: frontend
    image: misp-fe
    restart: unless-stopped
    depends_on:
      - misp
    volumes:
      - misp-source:/var/www/MISP
      - misp-config:/var/www/MISP/app/Config
      - misp-certificates:/etc/nginx/certs
      - misp-app-files:/var/www/MISP/app/files
      - misp-app-tmp:/var/www/MISP/app/tmp
    ports:
      - 80:80
      - 443:443
    networks:
      misp-backend:
        aliases:
          - ${FRONTEND_CONTAINER_ALIAS}

  database:
    build: db
    image: misp-db
    restart: always
    env_file: .env
    depends_on:
      - misp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - misp-database:/var/lib/mysql
    networks:
      misp-backend:
        aliases:
          - ${DB_CONTAINER_ALIAS}

  modules:
    build: modules
    image: misp-modules
    restart: always
    networks:
      misp-backend:
        aliases:
          - ${MODULES_CONTAINER_ALIAS}

  redis:
    image: redis:latest
    restart: always
    networks:
      misp-backend:
        aliases:
          - ${REDIS_CONTAINER_ALIAS}
    command: "redis-server --appendonly yes"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      misp-backend:
        aliases:
          - ${REDIS_COMMANDER_CONTAINER_ALIAS}

  worker_default:
    << : *worker-container
    environment:
      queue: default

  worker_email:
    << : *worker-container
    environment:
      queue: email 

  worker_prio:
    << : *worker-container
    environment:
      queue: prio 

  worker_cache:
    << : *worker-container
    environment:
      queue: cache 

  worker_scheduler:
    << : *worker-container
    environment:
      queue: scheduler 

  worker_update:
    << : *worker-container
    environment:
      queue: update
