version: '3.1'

networks:
  misp-backend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "mispbr0"
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
        - subnet: "192.168.66.0/28"

volumes:
  misp-source:
  misp-config:
  misp-logs:

services:
  misp:
    build: misp
    image: misp
    restart: unless-stopped
    volumes:
      - misp-source:/var/www/MISP
      - misp-config:/var/www/MISP/app/Config
    networks:
      misp-backend:
        aliases:
          - ${MISP_CONTAINER_ALIAS}
    env_file:
      - .worker.env 
      - .env

  #misp-configurator:
  #  build: misp-configurator
  #  image: misp-configurator
  #  volumes:
  #    - misp-source:/var/www/MISP
  #    - misp-config:/var/www/MISP/app/Config

  frontend:
    build: frontend
    image: misp-fe
    restart: unless-stopped
    depends_on:
      - misp
    volumes:
      - misp-source:/var/www/MISP
      - misp-config:/var/www/MISP/app/Config
    ports:
      - 80:80
      - 443:443
    networks:
      misp-backend:
        aliases:
          - ${FRONTEND_CONTAINER_ALIAS}

  database:
    build: db
    image: misp-db
    restart: always
    env_file: .env
    depends_on:
      - misp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #healthcheck:
    #  test: ["CMD-SHELL", "mysqladmin -u root -p ${MYSQL_ROOT_PASSWORD} ping "]
    #  interval: 10s
    #  timeout: 2s
    #  retries: 5
    networks:
      misp-backend:
        aliases:
          - ${DB_CONTAINER_ALIAS}

  modules:
    build: modules
    image: misp-modules
    restart: always
    networks:
      misp-backend:
        aliases:
          - ${MODULES_CONTAINER_ALIAS}


  redis:
    image: redis:latest
    restart: always
    networks:
      misp-backend:
        aliases:
          - redis
    command: "redis-server --appendonly yes"


  worker_default:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue default --log-handler Console -v -d'" 
    env_file:
      - .worker.env

  worker_email:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue email --log-handler Console -v -d'" 
    env_file:
      - .worker.env



  worker_prio:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue prio --log-handler Console -v -d'" 
    env_file:
      - .worker.env


  worker_cache:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue cache --log-handler Console -v -d'" 
    env_file:
      - .worker.env

  worker_scheduler:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue scheduler --log-handler Console -v -d'" 
    env_file:
      - .worker.env

  worker_update:
    build: misp
    image: misp
    restart: always
    volumes:
      - misp-source:/var/www/MISP:rw
      - misp-config:/var/www/MISP/app/Config
    depends_on:
      - misp
    networks:
      misp-backend:
    command: "/bin/sh -c 'cd /var/www/MISP/app/Console/Command && ../cake CakeResque.CakeResque start --interval 5 --queue update --log-handler Console -v -d'" 
    env_file:
      - .worker.env
